### ISSUE TITLE
[Enhancement] Add Lingua Libre as additional source

### ISSUE THREAD

**Issue by homocomputeris** [Rascalov/Anki-Simple-Forvo-Audio#19]
Lingua Libre is pronunciation bank by Wikimedia France

https://lingualibre.org/wiki/LinguaLibre:Explore_the_sound_library

**Comment by Rascalov** [comment]
Looks promising, I'll look into how to make it work.

**Comment by Rascalov** [comment]
Alright, I think I finished scouting the website and going through the scenarios (which didn't take very long since wikimedia does not obfuscate downloading options as Forvo did). 
It's a cool project, even allowing me to download all their datasets straight up.

I think the best course is to use the search feature, visit the page of the result(s) that matches exactly (maybe ignore punctuation), then move to its page, afterwards I can look for the `ogg` file reference to upload.wikimedia and start downloading. 

Naming scheme will probably be the same as I do for Forvo. 
I will probably put the Lingua Libre audios on the top of the results since they seem to be pretty good quality.  

If I don't encounter any issues, this should be done at the end of the week if not sooner.

**Comment by Rascalov** [comment]
The initial edits I made seem promising, even though lingua libre uses a slightly different language code, it seems compatible with the forvo language list from what I've tested. 
The results from this source are marked by a `Q` as shown below:
![image](https://github.com/Rascalov/Anki-Simple-Forvo-Audio/assets/31393063/62f0f20c-ee42-4d92-b6f2-b9a3b9eac473)

The additional source does make the extension take slightly longer with its search, so I decided to make this a configuration option 
![image](https://github.com/Rascalov/Anki-Simple-Forvo-Audio/assets/31393063/a336511b-0f68-4371-adc4-5b9f4a621149)

I will probably merge the changes and release a new version at the end of the week. 

### If you would like to test the changes before then (which I encourage, cause I only checked Dutch, English and Russian) 
You can download the [LinugaLibre Branch](https://github.com/Rascalov/Anki-Simple-Forvo-Audio/tree/LinguaLibreSupport) and replace the `bs4Scraper.py` and `ForvoTTS.py` in your addon folder with the files included in the downloaded branch. Then you need to add the `"Use sources besides Forvo": "True"` variable to your addon config, as shown in the previous screenshot, to enable the Lingua Libre as a source!

**Comment by Rascalov** [comment]
It is done, I merged the changes on https://github.com/Rascalov/Anki-Simple-Forvo-Audio/pull/20
Ankiweb now has the updated addon. You can either download the addon again from their site, or check for updates inside the anki addon menu. 

Closing this issue, marking its completion

**Comment by homocomputeris** [comment]
Thanks a lot!
