### ISSUE TITLE
Bug when adding audio, deleting it, and then adding it do a different field

### ISSUE THREAD

**Issue by Expertium** [Rascalov/Anki-Simple-Forvo-Audio#26]
```
Caught exception:
Traceback (most recent call last):
  File "C:\Users\Andrew\AppData\Roaming\Anki2\addons21\560814150\ForvoTts.py", line 173, in <lambda>
    addButton.clicked.connect(lambda: self.insertIntoCard(ankiAudioObject))
  File "C:\Users\Andrew\AppData\Roaming\Anki2\addons21\560814150\ForvoTts.py", line 196, in insertIntoCard
    os.rename(fullpath, self.getDefinteConfigPath() + ankiAudioObject.getBucketFilename())
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\Andrew\\AppData\\Roaming\\Anki2\\User 1\\collection.media\\TEMP_AUDIO_FILE-立場-869928.mp3' -> 'C:\\Users\\Andrew\\AppData\\Roaming\\Anki2\\User 1\\collection.media\\立場-869928.mp3'
```
Context: I have accidentally added the audio to the wrong field. I deleted it, and then tried adding it to a different field, then got this error. Deleting the file from the media folder and restarting Anki helped.

**Comment by Rascalov** [comment]
Thank you for the report!
Interesting, I did not have success in reproducing the bug. I attached a gif of the steps I took, let me know if that differs from how  you came across this error. 
![output](https://github.com/Rascalov/Anki-Simple-Forvo-Audio/assets/31393063/711af8fb-7c55-4247-83df-870c343f3c23)

I also tried deleting the media after and then previewing and adding the audio to a different card, but that also did not produce an error.
It could also be a windows specific error since Linux and Windows might have different rules for `os.rename`. I'll have to test it on a Windows machine at some point.

**Comment by Expertium** [comment]
Hm, strange. Either there is some other condition for this bug to appear, or this is Windows-specific, as you said.

**Comment by Rascalov** [comment]
I'm betting on windows-specific, doesn't mean I won't address it of course :3 
I assume you have been able to reproduce the bug with the steps you outlined for me?

**Comment by Rascalov** [comment]
It seems I should have just looked up the method on the documentation
https://docs.python.org/3/library/os.html#os.rename
```
On Windows, if dst exists a FileExistsError is always raised. The operation may fail if src and dst are on different filesystems.
```

so I should probably change it to `os.replace()` , which would silently overwrite the existing file (same behavior as Unix's `os.rename()`)
